blank_issues_enabled: false
contact_links:

  - name: ðŸ’¬ Ask on Discord
    url: https://discord.gg/xuDmpbEDnQ
    about: Real-time communication with maintainers, contributors, and broader community
